### ISSUE TITLE
no more https://developers.google.com/accounts/docs/AuthForInstalledApps ?

### ISSUE THREAD

**Issue by PierreCrescenzo** [deong/charrington#6]
Hello,

Since this morning, the very great charrigton don't work. :-( The new message is:
"
Traceback (most recent call last):
  File "/home/pierre/tmp/logiciels/charrington/charrington.py", line 563, in <module>
    acctgroups = get_all_contact_groups(acct)
  File "/home/pierre/tmp/logiciels/charrington/charrington.py", line 160, in get_all_contact_groups
    gdc.ClientLogin(acct["login"], acct["password"], gdc.source)
  File "/usr/lib/python2.7/dist-packages/gdata/client.py", line 441, in client_login
    captcha_token=captcha_token, captcha_response=captcha_response)
  File "/usr/lib/python2.7/dist-packages/gdata/client.py", line 373, in request_client_login_token
    response, ClientLoginFailed, response_body)
gdata.client.ClientLoginFailed: Server responded to ClientLogin request: 404, https://developers.google.com/accounts/docs/AuthForInstalledApps
"

This is a new problem of my Linux (Debian testing+stable) or of charrington?

Thank you very much.

Best regards,

Pierre Crescenzo

**Comment by deong** [comment]
Google recently turned off the authentication mechanism I'm using. Everything has to be oauth now, and I haven't had time to look into switching it over. I'd like to get it fixed, but I probably won't have time for another month or so. Sorry for the inconvenience.
